# Generated by Django 4.1.3 on 2022-12-05 22:03

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_files_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(blank=True, default='', upload_to=api.models.upload_to),
        ),
    ]
