# Generated by Django 4.1.3 on 2022-12-05 22:11

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_files_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('file', models.FileField(blank=True, default='', upload_to=api.models.upload_to)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task', verbose_name='file')),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
