# Generated by Django 4.1.3 on 2022-12-05 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_file_delete_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.task'),
        ),
    ]
